FROM node AS build

WORKDIR /app

COPY frontend/package*.json ./

RUN npm install

COPY frontend/ .

COPY .env .env

RUN npm run build

FROM nginx:stable-alpine

COPY --from=build /app/dist /usr/share/nginx/html

COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /usr/share/nginx/html

EXPOSE 82

CMD ["nginx", "-g", "daemon off;"]