# build env
FROM node AS build

WORKDIR /app

COPY frontend/package*.json ./

RUN npm install

# Copy app source
COPY frontend/ .

# Copy shared .env from root (χάρη στο context: .)
COPY .env .env

RUN npm run build

# production env
FROM nginx:stable-alpine

COPY --from=build /app/dist /usr/share/nginx/html

COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /usr/share/nginx/html

EXPOSE 82

CMD ["nginx", "-g", "daemon off;"]