services:
  frontend:
    depends_on:
      backend:
        condition: service_started
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    env_file:
      - .env    
    restart: always
    ports:
      - "${FRONTEND_HOST_PORT}:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    container_name: backend
    build: backend/
    restart: always
    depends_on:
      mongodb:
        condition: service_started
    env_file:
      - .env    
    ports:
      - "${BACKEND_HOST_PORT}:8080"
    volumes:
      -  ./backend/app:/code/app

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - "${MONGO_CONTAINER_PORT}:27017"
    env_file:
      - .env 
    volumes:
      - ./mongodb/db:/data/db:rw