services:
  graspos-frontend:
    depends_on:
      graspos-backend:
        condition: service_started
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: frontend

    ports:
      - "80:82"
    env_file:
      - .env
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - api_bridge

  graspos-backend:
    container_name: graspos-backend
    build: backend/
    restart: always
    depends_on:
      mongodb:
        condition: service_started
    env_file:
      - .env
    ports:
      - "${BACKEND_HOST_PORT}:8080"
    volumes:
      - ./backend/app:/code/app
    networks:
      - api_bridge

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - "${MONGO_CONTAINER_PORT}:27017"
    env_file:
      - .env
    volumes:
      - ./mongodb/db:/data/db:rw
    networks:
      - api_bridge

networks:
  api_bridge:
    driver: bridge
